### ISSUE TITLE
ST32 Driver won't install [Windows 10]

### ISSUE THREAD

**Issue by number-g** [DJPlaya/Tesseract-Cobra#4]
When I try to install the ST32 driver in Win10 the installer fails.

It says: "Errors were encountered while installing the software for your devices. See the Status column for more details.

Sometimes it helps to run this wizard again. If that doesn't work, contact your device vendor"

The only information in the Status column is the text "Install failed"

And I have tried running it again a few times, rebooting, etc.

**Comment by DJPlaya** [comment]
Sorry for the late Reply.
Check if some other Version like the Win7 does work.
If it still fails, try Compatibility Mode.

It may be an Alternative to install the Driver yourself by adding the inf File as legacy hardware in the device manager, at least thats what i would try.
It also wouldn't hurt to install the Security catalog (.cat) File, since we already have that.
Finally, the x64/STTub30.sys belongs into System32/drivers .

I no longer have Hardware to test, hope this helps you with fixing your Device(s), otherwise i would recommend contacting Nolo, their Support was very nice to me.

**Comment by DJPlaya** [comment]
Timeout
